// Disciplina   : Técnicas de Desenvolvimento de Algoritmos
// Autor(a)    : Walmirino Neto
// Data atual  : 04/10/2022

algoritmo "exemplo1_multiplicacao"

var // Seção de Declarações das variáveis
n1, n2, m: real

inicio // Seção de Comandos, procedimento, funções, operadores, etc...
       escreval("digite dois numeros")
       leia(n1)
       leia(n2)
       m <- n1 * n2
       escreva("multiplicacao = ", m)

fimalgoritmo