// Disciplina  : Técnicas de Desenvolvimento de Algoritmos
// Autor(a)    : Walmirino Neto
// Data atual  : 06/10/2022

algoritmo "exemplo1_para_(for)"


var // Seção de Declarações das variáveis
i: inteiro

inicio // Seção de Comandos, procedimento, funções, operadores, etc...

// for ($i=0; $i<=5; $i++) {
//    echo "Valor de i: {$i}";
// }
para i de 0 ate 5 passo 1 faca
   escreval("Valor de i:",i)
fimpara

fimalgoritmo