/* CRIANDO A TABELA COM PRIMARY KEY E CAMPO DE DADOS UNICO */
CREATE TABLE ESTADO
(
    SG_ESTADO       CHAR(2),
    NM_ESTADO       VARCHAR2(35),
    CONSTRAINT PK_ESTADO_SG_ESTADO PRIMARY KEY (SG_ESTADO),
    CONSTRAINT UN_ESTADO_NM_ESTADO UNIQUE (NM_ESTADO)
);

/* CRIANDO A TABELA COM PRIMARY KEY */
CREATE TABLE CLIENTE
(
    CD_CLIENTE      NUMBER(4),
    NM_CLIENTE      VARCHAR2(50),
    DS_ENDERECO     VARCHAR2(70),
    CD_MUNICIPIO    CHAR(5),
    SG_ESTADO       CHAR(2),
    NR_CEP          VARCHAR2(8),
    NR_DDD          NUMBER(3),
    NR_FONE         NUMBER(9),
    IE_SEXO         CHAR(1),
    CONSTRAINT PK_CLIENTE_CD_CLIENTE PRIMARY KEY (CD_CLIENTE)
);

/* CRIANDO A TABELA COM PRIMARY KEY COMPOSTA */
CREATE TABLE HISTORICO
(
    CD_CLIENTE      NUMBER(4),
    DT_COMPRA       DATE,
    VL_COMPRA       NUMBER(12,2),
    CONSTRAINT PK_HISTORICO PRIMARY KEY (CD_CLIENTE, DT_COMPRA)
);


/* REMOVENDO A TABELA */
DROP TABLE CLIENTE;

/* CRIANDO A TABELA COM PRIMARY KEY E FOREIGN KEY */
CREATE TABLE CLIENTE
(
    CD_CLIENTE      NUMBER(4),
    NM_CLIENTE      VARCHAR2(50),
    DS_ENDERECO     VARCHAR2(70),
    CD_MUNICIPIO    CHAR(5),
    SG_ESTADO       CHAR(2),
    NR_CEP          VARCHAR2(8),
    NR_DDD          NUMBER(3),
    NR_FONE         NUMBER(9),
    IE_SEXO         CHAR(1),
    CONSTRAINT PK_CLIENTE_CD_CLIENTE PRIMARY KEY (CD_CLIENTE),
    CONSTRAINT FK_CLIENTE_SG_ESTADO FOREIGN KEY (SG_ESTADO) REFERENCES ESTADO (SG_ESTADO)
);

/* REMOVENDO A TABELA */
DROP TABLE CLIENTE;

/* CRIANDO A TABELA  COM PRIMARY KEY, FOREIGN KEY E CHECK */
CREATE TABLE CLIENTE
(
    CD_CLIENTE      NUMBER(4),
    NM_CLIENTE      VARCHAR2(50),
    DS_ENDERECO     VARCHAR2(70),
    CD_MUNICIPIO    CHAR(5),
    SG_ESTADO       CHAR(2),
    NR_CEP          VARCHAR2(8),
    NR_DDD          NUMBER(3),
    NR_FONE         NUMBER(9),
    IE_SEXO         CHAR(1),
    CONSTRAINT PK_CLIENTE_CD_CLIENTE PRIMARY KEY (CD_CLIENTE),
    CONSTRAINT FK_CLIENTE_SG_ESTADO FOREIGN KEY (SG_ESTADO) REFERENCES ESTADO (SG_ESTADO),
    CONSTRAINT CK_CLIENTE_IE_SEXO CHECK (IE_SEXO IN ('F', 'M'))
);

/* REMOVENDO A TABELA */
DROP TABLE CLIENTE;

/* CRIANDO A TABELA COM PK, FK, CH E NOT NULL */
CREATE TABLE CLIENTE
(
    CD_CLIENTE      NUMBER(4),
    NM_CLIENTE      VARCHAR2(50) NOT NULL,
    DS_ENDERECO     VARCHAR2(70) NOT NULL,
    CD_MUNICIPIO    CHAR(5),
    SG_ESTADO       CHAR(2),
    NR_CEP          VARCHAR2(8),
    NR_DDD          NUMBER(3),
    NR_FONE         NUMBER(9),
    IE_SEXO         CHAR(1),
    CONSTRAINT PK_CLIENTE_CD_CLIENTE PRIMARY KEY (CD_CLIENTE),
    CONSTRAINT FK_CLIENTE_SG_ESTADO FOREIGN KEY (SG_ESTADO) REFERENCES ESTADO (SG_ESTADO),
    CONSTRAINT CK_CLIENTE_IE_SEXO CHECK (IE_SEXO IN ('F', 'M'))
);

/* ACRESCENTAR UM CAMPO EM UMA TABELA */
ALTER TABLE CLIENTE
ADD( IE_FISICA_JURIDICA CHAR(1));

/* ALTERANDO OBRIGATORIEDADE DE ATRIBUTOS */
ALTER TABLE CLIENTE 
MODIFY (CD_CLIENTE NOT NULL);

/* ALTERANDO O TIPO DE ATRIBUTO */
ALTER TABLE CLIENTE
 MODIFY (DS_ENDERECO NUMBER(3));

/* ALTERANDO O TAMANHO DOS ATRIBUTOS */
ALTER TABLE CLIENTE
MODIFY (NR_CEP VARCHAR2(12));

/* ACRESCENTAR CONSTRAINT EM UMA TABELA */
ALTER TABLE CLIENTE
ADD CONSTRAINT CK_CLIENTE_IE_FISICA_JURIDICA
CHECK (IE_FISICA_JURIDICA IN('F','J'));

/* DESABILITANDO UMA CONSTRAINT */
ALTER TABLE CLIENTE
DISABLE CONSTRAINT CK_CLIENTE_IE_FISICA_JURIDICA; 

/* EXCLUIR UMA CONSTRAINT */
ALTER TABLE CLIENTE
DROP CONSTRAINT CK_CLIENTE_IE_FISICA_JURIDICA;

/* MOSTRAR TABELA */
DESC CLIENTE;