CREATE TABLE TB_CONTAS
(
 ID_CONTA NUMBER(10),
 NOME_CONTA VARCHAR2(50),
 CONSTRAINT PK_TB_CONTAS_ID_CONTA PRIMARY KEY (ID_CONTA)
);

INSERT INTO TB_CONTAS VALUES (1, 'CAIXA');
INSERT INTO TB_CONTAS VALUES (2, 'SERVICOS');
INSERT INTO TB_CONTAS VALUES (3, 'PRODUTOS');


CREATE TABLE TB_PEDIDOS
(
 ID_PEDIDO  NUMBER(10),
 VALOR NUMBER(10,2),
 ID_CONTA NUMBER(10),
 CONSTRAINT PK_TB_PEDIDOS_ID_PEDIDO PRIMARY KEY (ID_PEDIDO),
 CONSTRAINT FK_TB_PEDIDOS_ID_CONTA FOREIGN KEY (ID_CONTA) REFERENCES TB_CONTAS (ID_CONTA)
);

INSERT INTO TB_PEDIDOS VALUES (1, 120.00, 1);
INSERT INTO TB_PEDIDOS VALUES (2, 1300.00, 2);
INSERT INTO TB_PEDIDOS VALUES (3, 9800.00, 2);
INSERT INTO TB_PEDIDOS VALUES (4, 1500.00, 3);
INSERT INTO TB_PEDIDOS VALUES (5, 100.00, 3);

CREATE OR REPLACE FUNCTION BALANCO (NUMCOUNT IN NUMBER)
    RETURN NUMBER
    IS
    CONTA_BALANCO NUMBER(10,2);
BEGIN
    SELECT SUM(VALOR) INTO CONTA_BALANCO
    FROM TB_PEDIDOS
    WHERE ID_CONTA = NUMCOUNT;
    
    RETURN (CONTA_BALANCO);
END;

SELECT ID_CONTA, NOME_CONTA, BALANCO(ID_CONTA) FROM TB_CONTAS;
