/* FUNCAO DE GRUPO */
SELECT AVG(SALARY) FROM EMPLOYEES;   /* MEDIA */
SELECT SUM(SALARY) FROM EMPLOYEES;   /* SOMA */
SELECT COUNT(SALARY) FROM EMPLOYEES; /* NUMERO DE LINHAS */
SELECT MAX(SALARY) FROM EMPLOYEES;   /* MAIOR VALOR */
SELECT MIN(SALARY) FROM EMPLOYEES;   /* MENOR VALOR */

/* GROUP BY */
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

/* GROUP BY - SEM O CAMPO NO SELECT */
SELECT AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

/* GROUP BY E ORDER BY */
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP by DEPARTMENT_ID
ORDER by DEPARTMENT_ID;

/* AGRUPAMENTO COMPOSTO */
SELECT DEPARTMENT_ID DEPT_ID, JOB_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY DEPT_ID;

/* NAO USAR FUNCAO DE GRUPO NO WHERE */
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
WHERE AVG(salary) > 8000
GROUP BY DEPARTMENT_ID;

/* ISSO VAI DAR ERRO POR CAUSA DO WHERE */
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID Not in (10,20,30)
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

/* MEDIA SALARIAL E SOMA DOS SALARIOS POR DEPARTAMENTO E CARGO */
SELECT DEPARTMENT_ID, Job_ID, AVG(SALARY), Sum(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, Job_ID
ORDER BY DEPARTMENT_ID; 

/* USANDO O HAVING (semelhante ao WHERE) */
SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY) > 10000;

SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 6000
ORDER BY DEPARTMENT_ID;

/* QUANTIDADE DE EMPREGADOS POR DEPARTAMENTO COM SALARIO ACIMA DE 10000 */
SELECT DEPARTMENT_ID, Count(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY) > 10000
ORDER BY DEPARTMENT_ID;

