/* 
%TYPE – Herança de tipo e tamanho
*/
SET SERVEROUTPUT ON

DECLARE
    V_EMP_HIREDATE EMPLOYEES.HIRE_DATE%TYPE; 
    V_EMP_SALARY EMPLOYEES.SALARY%TYPE; 
BEGIN
    SELECT HIRE_DATE, SALARY
    INTO V_EMP_HIREDATE, V_EMP_SALARY
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 100; 
    DBMS_OUTPUT.PUT_LINE(V_EMP_SALARY|| ' ' || V_EMP_HIREDATE);
END;
