/* 
 Incluindo dados na tabela de empregados
*/
SET SERVEROUTPUT ON

BEGIN
    INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, SALARY)
    VALUES (EMPLOYEES_SEQ.NEXTVAL, 'Ruth', 'Cores', 'RCORES', SYSDATE, 'AD_ASST', 4000);
END;
